// Vocabulary data for Kannada word learning game
const vocabulary = [
    { english: "appreciation", kannada: "ಮೆಚ್ಚುಗೆ" },
    { english: "art", kannada: "ಕಲೆ" },
    { english: "background", kannada: "ಹಿನ್ನೆಲೆ" },
    { english: "banana", kannada: "ಬಾಳೆ" },
    { english: "bed", kannada: "ಮಂಚ" },
    { english: "bird", kannada: "ಹಕ್ಕಿ" },
    { english: "bird chirp", kannada: "ಕಲರವ" },
    { english: "blacksmith", kannada: "ಕಮ್ಮಾರ" },
    { english: "Brahma", kannada: "ಬ್ರಹ್ಮ" },
    { english: "brick", kannada: "ಇಟ್ಟಿಗೆ" },
    { english: "building", kannada: "ಕಟ್ಟಡ" },
    { english: "business", kannada: "ವ್ಯಾಪಾರ" },
    { english: "buttermilk", kannada: "ಮಜ್ಜಿಗೆ" },
    { english: "cat", kannada: "ಬೆಕ್ಕು" },
    { english: "charcoal", kannada: "ಇದ್ದಿಲು" },
    { english: "charioteer", kannada: "ಸಾರಥಿ" },
    { english: "clap", kannada: "ಚಪ್ಪಾಳೆ" },
    { english: "cloth", kannada: "ಬಟ್ಟೆ" },
    { english: "darkness", kannada: "ಮಬ್ಬು" },
    { english: "design", kannada: "ಚಿತ್ತಾರ" },
    { english: "direction", kannada: "ದಿಕ್ಕು" },
    { english: "drumstick", kannada: "ನುಗ್ಗೆಕಾಯಿ" },
    { english: "dry tree", kannada: "ಒಣಮರ" },
    { english: "elephant", kannada: "ಆನೆ" },
    { english: "encouragement", kannada: "ಉತ್ತೇಜನ" },
    { english: "eye", kannada: "ಕಣ್ಣು" },
    { english: "fathom", kannada: "ಅಗಲ" },
    { english: "festival", kannada: "ಉಟ್ಸವ" },
    { english: "fire", kannada: "ಬೆಂಕಿ" },
    { english: "full moon", kannada: "ಹುಣ್ಣಿಮೆ" },
    { english: "goal", kannada: "ಲಕ್ಷ್ಯ" },
    { english: "goldsmith", kannada: "ಅಕ್ಕಸಾಲಿಗ" },
    { english: "grandfather", kannada: "ಅಜ್ಜ" },
    { english: "grass", kannada: "ಹುಲ್ಲು" },
    { english: "handloom", kannada: "ಕೈಮಗ್ಗ" },
    { english: "happiness", kannada: "ಸಂತೋಷ" },
    { english: "highway", kannada: "ಹೆದ್ದಾರಿ" },
    { english: "innovation", kannada: "ನವೀನತೆ" },
    { english: "iron", kannada: "ಕಬ್ಬಿಣ" },
    { english: "jasmine", kannada: "ಮಲ್ಲಿಗೆ" },
    { english: "juice", kannada: "ರಸ" },
    { english: "kindness", kannada: "ದಯೆ" },
    { english: "loss", kannada: "ನಷ್ಟ" },
    { english: "lotus", kannada: "ಕಮಲ" },
    { english: "lullaby", kannada: "ಜೋಗುಳ" },
    { english: "matrilineal", kannada: "ತಾಯ್ತನ" },
    { english: "medal", kannada: "ಪದಕ" },
    { english: "mind", kannada: "ಮನಸ್ಸು" },
    { english: "moon", kannada: "ಚಂದ್ರ" },
    { english: "nature", kannada: "ಪ್ರಕೃತಿ" },
    { english: "neck", kannada: "ಕುತ್ತಿಗೆ" },
    { english: "need", kannada: "ಅಗತ್ಯ" },
    { english: "ocean", kannada: "ಸಮುದ್ರ" },
    { english: "oil", kannada: "ಎಣ್ಣೆ" },
    { english: "pain", kannada: "ನೋವು" },
    { english: "pickle", kannada: "ಉಪ್ಪಿನಕಾಯಿ" },
    { english: "pride", kannada: "ಹೆಮ್ಮೆ" },
    { english: "promise", kannada: "ಕರಾರು" },
    { english: "python", kannada: "ಹೆಬ್ಬಾವು" },
    { english: "ragi ball", kannada: "ರಾಗಿ ಮುದ್ದೆ" },
    { english: "saw", kannada: "ಗರಗಸ" },
    { english: "science", kannada: "ವಿಜ್ಞಾನ" },
    { english: "seashell", kannada: "ಕಪ್ಪೆಚಿಪ್ಪು" },
    { english: "silence", kannada: "ಮೌನ" },
    { english: "situation", kannada: "ಸನ್ನಿವೇಶ" },
    { english: "snake", kannada: "ಹಾವು" },
    { english: "soil", kannada: "ಮಣ್ಣು" },
    { english: "soldier", kannada: "ಸೈನಿಕ" },
    { english: "spectacles", kannada: "ಕನ್ನಡಕ" },
    { english: "sprout", kannada: "ಮೊಳಕೆ" },
    { english: "star", kannada: "ನಕ್ಷತ್ರ" },
    { english: "sunflower", kannada: "ಸೂರ್ಯಕಾಂತಿ" },
    { english: "sweet potato", kannada: "ಸಿಹಿಗೆಣಸು" },
    { english: "swing", kannada: "ತೊಟ್ಟಿಲು" },
    { english: "tap", kannada: "ನಳ" },
    { english: "teacher", kannada: "ಗುರುಗಳು" },
    { english: "tears", kannada: "ಕಣ್ಣೀರು" },
    { english: "volcano", kannada: "ಜ್ವಾಲಾಮುಖಿ" },
    { english: "west", kannada: "ಪಶ್ಚಿಮ" },
    { english: "window", kannada: "ಕಿಟಕಿ" },
    { english: "work", kannada: "ಕೆಲಸ" }
];