// Vocabulary data for Kannada word learning game
// Format: [english, kannada]
const vocabulary = [
    ["appreciation", "ಮೆಚ್ಚುಗೆ"],
    ["age", "ವಯಸ್ಸು"],
    ["art", "ಕಲೆ"],
    ["background", "ಹಿನ್ನೆಲೆ"],
    ["banana", "ಬಾಳೆ"],
    ["bed", "ಶಯ್ಯೆ"],
    ["bird", "ಹಕ್ಕಿ"],
    ["bird chirp", "ಕಲರವ"],
    ["blacksmith", "ಕಮ್ಮಾರ"],
    ["blessings", "ಅಶೀರ್ವಾದ"],
    ["book", "ಪುಸ್ತಕ"],
    ["Brahma", "ಬ್ರಹ್ಮ"],
    ["brick", "ಇಟ್ಟಿಗೆ"],
    ["bud", "ಮೊಗ್ಗು"],
    ["building", "ಕಟ್ಟಡ"],
    ["business", "ವ್ಯಾಪಾರ"],
    ["buttermilk", "ಮಜ್ಜಿಗೆ"],
    ["cat", "ಬೆಕ್ಕು"],
    ["celebrate", "ಆಚರಿಸು"],
    ["charcoal", "ಇದ್ದಿಲು"],
    ["charioteer", "ಸಾರಥಿ"],
    ["cheerfulness", "ಉಲ್ಲಾಸ"],
    ["city", "ಊರು"],
    ["clap", "ಚಪ್ಪಾಳೆ"],
    ["cloth", "ಬಟ್ಟೆ"],
    ["cool", "ತಂಪು"],
    ["darkness", "ಮಬ್ಬು"],
    ["design", "ಚಿತ್ತಾರ"],
    ["daal", "ತೊವ್ವೆ"],
    ["decision", "ನಿರ್ಧಾರ"],
    ["direction", "ದಿಕ್ಕು"],
    ["drumstick", "ನುಗ್ಗೆಕಾಯಿ"],
    ["dry tree", "ಒಣಮರ"],
    ["east", "ಪೂರ್ವ"],    
    ["elephant", "ಆನೆ"],
    ["encouragement", "ಉತ್ತೇಜನ"],
    ["eye", "ಕಣ್ಣು"],
    ["fathom", "ಅಗಲ"],
    ["festival", "ಉಟ್ಸವ"],
    ["fire", "ಬೆಂಕಿ"],
    ["focus", "ಲಕ್ಷ್ಯ"],
    ["full moon", "ಹುಣ್ಣಿಮೆ"],
    ["friend", "ಸ್ನೇಹಿತ"],
    ["goldsmith", "ಅಕ್ಕಸಾಲಿಗ"],
    ["government", "ಸರ್ಕಾರ"],
    ["grandfather", "ಅಜ್ಜ"],
    ["grass", "ಹುಲ್ಲು"],
    ["handloom", "ಕೈಮಗ್ಗ"],
    ["handstand asana", "ಶೀರ್ಷಾಸನ"],
    ["happiness", "ಸಂತೋಷ"],
    ["head", "ಶಿರಸ್ಸು"],
    ["highway", "ಹೆದ್ದಾರಿ"],
    ["innovation", "ನವೀನತೆ"],
    ["iron", "ಕಬ್ಬಿಣ"],
    ["jasmine", "ಮಲ್ಲಿಗೆ"],
    ["juice", "ರಸ"],
    ["kindness", "ದಯೆ"],
    ["knowledge", "ಜ್ಞಾನ"],
    ["less", "ಕಮ್ಮಿ"],
    ["letter (character)", "ಅಕ್ಷರ"],
    ["loss", "ನಷ್ಟ"],    
    ["lotus", "ಕಮಲ"],
    ["lullaby", "ಸುವ್ವಲಾಲಿ"],
    ["matrilineal", "ತಾಯ್ತನ"],
    ["medal", "ಪದಕ"],
    ["mind", "ಮನಸ್ಸು"],
    ["moon", "ಚಂದ್ರ"],
    ["mother", "ಅವ್ವ"],    
    ["nature", "ಪ್ರಕೃತಿ"],
    ["neck", "ಕುತ್ತಿಗೆ"],
    ["need", "ಅಗತ್ಯ"],
    ["ocean", "ಸಮುದ್ರ"],
    ["oil", "ಎಣ್ಣೆ"],
    ["pain", "ನೋವು"],
    ["pickle", "ಉಪ್ಪಿನಕಾಯಿ"],
    ["place", "ಸ್ಥಳ"],
    ["pour", "ಹೊಯ್ಯು"],
    ["prayer", "ಪ್ರಾರ್ಥನೆ"],
    ["pride", "ಹೆಮ್ಮೆ"],
    ["procession", "ಉತ್ಸವ"],
    ["promise", "ಕರಾರು"],
    ["python", "ಹೆಬ್ಬಾವು"],
    ["ragi ball", "ರಾಗಿ ಮುದ್ದೆ"],
    ["saw", "ಗರಗಸ"],
    ["science", "ವಿಜ್ಞಾನ"],
    ["sea", "ಸಮುದ್ರ"],
    ["seashell", "ಕಪ್ಪೆಚಿಪ್ಪು"],
    ["sentence", "ವಾಕ್ಯ"],
    ["silence", "ಮೌನ"],
    ["silver", "ಬೆಳ್ಳಿ"],
    ["situation", "ಸನ್ನಿವೇಶ"],
    ["snake", "ಹಾವು"],
    ["soil", "ಮಣ್ಣು"],
    ["soldier", "ಸೈನಿಕ"],
    ["spectacles", "ಕನ್ನಡಕ"],
    ["sprout", "ಮೊಳಕೆ"],
    ["star", "ನಕ್ಷತ್ರ"],
    ["student", "ವಿದ್ಯಾರ್ಥಿ"],
    ["sugar crystal", "ಕಲ್ಲುಸಕ್ಕರೆ"],
    ["summer", "ಬೇಸಿಗೆ"],
    ["sunflower", "ಸೂರ್ಯಕಾಂತಿ"],
    ["sunrise", "ಸೂರ್ಯೋದಯ"],
    ["sunset", "ಸೂರ್ಯಾಸ್ತ"],
    ["sweet potato", "ಸಿಹಿಗೆಣಸು"],
    ["swing", "ಉಯ್ಯಾಲೆ"],
    ["tap", "ನಳ"],
    ["teacher", "ಗುರುಗಳು"],
    ["tears", "ಕಣ್ಣೀರು"],
    ["thorn", "ಮುಳ್ಳು"],
    ["volcano", "ಜ್ವಾಲಾಮುಖಿ"],
    ["west", "ಪಶ್ಚಿಮ"],
    ["window", "ಕಿಟಕಿ"],
    ["work", "ಕೆಲಸ"]
];